image: node:latest

stages:
  - deploy
  - build
  - test

install_dependencies:
  stage: build
  script:
    - chmod a+x build.sh && ./build.sh
  artifacts:
    paths:
      - module-comunicacao/node_modules/
      - module-integracao/node_modules/
      - module-notify/node_modules/
      - module-gateway/node_modules/

unit_tests:
  stage: test
  script:
    - chmod a+x tests.sh && ./tests.sh

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$NEW_SSH")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get install rsync
  script: 
    - ssh $SERVER_USER@$SERVER_IP
    - chmod a+x build.sh && ./build.sh
  only:
    - master