image: node:latest

stages:
  - test
  - build

test_bash:
  stage: test
  script: chmod a+x teste./bash && ./teste.bash

install_dependencies:
  stage: build
  script:
    - api-jaguar-commons/npm install
  artifacts:
    paths:
      - api-jaguar-commons/node_modules/