image: node:latest

stages:
  - deploy

install_dependencies:
  stage: build
  script:
    - chmod a+x build.sh && ./build.sh
  artifacts:
    paths:
      - module-comunicacao/node_modules/
      - module-integracao/node_modules/
      - module-notify/node_modules/
      - module-gateway/node_modules/

unit_tests:
  stage: test
  script:
    - chmod a+x tests.sh && ./tests.sh

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - rsync -avuz --exclude=".*" $CI_PROJECT_DIR $SERVER_USER@$SERVER_IP:~
    - ssh-add $SSH
    - ssh $SERVER_USER@$SERVER_IP
    - chmod a+x build.sh && ./build.sh
  only:
    - master