image: node:latest

stages:
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - chmod a+x build.sh && ./build.sh
  artifacts:
    paths:
      - module-comunicacao/node_modules/
      - module-integracao/node_modules/
      - module-notify/node_modules/
      - module-gateway/node_modules/

unit_tests:
  stage: test
  script:
    - chmod a+x tests.sh && ./tests.sh

deploy_docean:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat my_known_hosts >> ~/.ssh/known_hosts
    - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_CONN
    - cd api/api/jaguara_envios
    - chmod a+x build.sh && ./build.sh
  only:
    - master