image: node:latest

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - chmod a+x build.sh && ./build.sh
  artifacts:
    paths:
      - module-comunicacao/node_modules/
      - module-integracao/node_modules/
      - module-notify/node_modules/
      - module-gateway/node_modules/

unit_tests:
  stage: test
  script:
    - chmod a+x tests.sh && ./tests.sh
