image: node:latest

stages:
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - api-jaguar-commons/npm install
  artifacts:
    paths:
      - node_modules/