image: node:latest

stages:
  - deploy
  - build
  - test

install_dependencies:
  stage: build
  script:
    - chmod a+x build.sh && ./build.sh
  artifacts:
    paths:
      - module-comunicacao/node_modules/
      - module-integracao/node_modules/
      - module-notify/node_modules/
      - module-gateway/node_modules/

unit_tests:
  stage: test
  script:
    - chmod a+x tests.sh && ./tests.sh

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/ssh_key
    - echo $PRIVATE_KEY > ~/.ssh/ssh_key
    - ssh-add ~/.ssh/ssh_key
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script: 
    - ssh $SERVER_USER@$SERVER_IP
    - chmod a+x build.sh && ./build.sh
  only:
    - master