/**
 * Selectors enum to quickly change selector strings in cases WhatsApp FE changes structure/classes
 */
export enum Selectors {
    'QRCODE_IMG_PARENT_CLASS' = '._2EZ_m',
    'CONVERSATIONS_PARENT_CLASS' = '._1c8mz',
    'CONVERSATION_PLACEHOLDER_ELEMENT' = '._1AKfk',
    'CONVERSATION_MESSAGE_RESULTS_ELEMENT' = '._34xP_',
    'CONVERSATION_TARGET_ELEMENT' = '._2xINO',
    'CONVERSATION_SEARCH_INPUT_ELEMENT' = '._2zCfw',
    'CONVERSATION_CLEAR_SEARCH' = '._3Burg',
    'CHAT_MESSAGE_FIELD_SELECTOR' = '._2S1VP',
    'CHAT_SEND_BUTTON_SELECTOR' = '._35EW6'
}

/**
 * OLD VERSION ENUMS
 * //'CONVERSATIONS_PARENT_CLASS' = '.RLfQR',
 * //'CONVERSATION_SEARCH_INPUT_ELEMENT' = '.jN-F5',
 * 'CONVERSATION_PLACEHOLDER_ELEMENT' = '._1AKfk',
 * 'CONVERSATION_TARGET_ELEMENT' = '._25Ooe',
 */
